#!/bin/bash

# IN THIS EXAMPLE CHARMM'S THERMODYNAMIC INTEGRATION (PERT) ROUTINES ARE TESTED FOR SINGLE POINT ENERGIES.
# THE SYSTEM EXAMINED IS PHF IN A SOLVENT BOX, CENTRAL CHARGES ARE USED TO ALLOW DIRECT COMPARISON WITH
# STANDARD CHARMM ROUTINES. THE LAMBDA=0 STATE HAS FULL CHARGES, THE LAMBDA=1 STATE HAS ZERO CHARGES, THE
# ENERGIES CORRESPOND TO LAMBDA VALUES OF 0.0, 0.7 AND 1.0. PME IS USED FOR ELECTROSTATICS.

LOG1=fmdcm_water_ref.log
LOG2=fmdcm_water_dev.log

[[ -f $LOG1 ]] && rm $LOG1
[[ -f $LOG2 ]] && rm $LOG2

ulimit -s 10240

mpirun -np $NPROC $REFCHARMM -i fmdcm_water.inp -o $LOG1 >& errlog1
mpirun -np $NPROC $DEVCHARMM -i fmdcm_water.inp -o $LOG2 >& errlog2

echo "H2O WITH FLEXIBLE CHARGE POISTIONS (FMDCM), STABLE VS. DEVELOPMENT DCM TEST"
echo
echo $LOG1
for i in "ENER>" "ENER INTERN>" "ENER EXTERN>" "ENER IMAGES>" "ENER EWALD>"; do grep "$i" $LOG1 | tail -1; done

echo $LOG2
for i in "ENER>" "ENER INTERN>" "ENER EXTERN>" "ENER IMAGES>" "ENER EWALD>"; do grep "$i" $LOG2 | tail -1; done
echo
echo "CHECK FORCES AND VIRIAL:"
grep " ( WAT" $LOG2

