#!/bin/bash

# BENCHMARK TEST FOR DCM CODE WITH 10 OFF-CENTER CHARGES VS REFERENCE DCM CODE. NOTE THAT THE WATER
# MODEL IS FOR BENCHMARKING PURPOSES ONLY AND IS NOT MEANINGFUL. A SHORT MINIMIZATION IS FOLLOWED BY
# HEATING DURING A SHORT DYNAMICS RUN. SMOOTH "FSHIFTED" CUTOFFS ARE USED WITHOUT EWALD SUMMATION BUT
# WITH POLARIZABLE ATOMS

LOG1=waterbox-ref.out
LOG2=waterbox-dcm.out

[[ -f $LOG1 ]] && rm $LOG1
[[ -f $LOG2 ]] && rm $LOG2

ulimit -s 10240

echo
echo "POLARIZATION WITH 10-CHG MODEL: DEV DCM CODE VS REFERENCE DCM CODE"
echo "200 SD MINIMIZATION STEPS"
echo "REFERENCE CODE"
time mpirun -np $NPROC $REFCHARMM -i waterbox-dcm.inp -o $LOG1 >& errlog1

echo
echo "NEW CODE"
time mpirun -np $NPROC $DEVCHARMM -i waterbox-dcm.inp -o $LOG2 >& errlog2



