#!/bin/bash

# THIS TEST CHECKS STABILITY FOR A TRIPEPTIDE SYSTEM WHERE TERMINAL GROUPS WERE ADDED MANUALLY IN THE
# "REF" CASE VIA THE TOPOLOGY AND DCM PARAMETER FILES (TERMINAL GROUP CHARGES WERE ALSO CORRECTED TO
# PRODUCE A NEUTRAL / CORRECT NET CHARGE FOR THE SYSTEM)
# FOR THE "DEV" CASE THE DCM PATCHING ROUTINE IS INVOKED TO AUTOMATICALLY ADD THE TERMINAL GROUPS AND
# CORRECT THE CHARGES TO MAINTAIN NEUTRALITY / NET CHARGE OF THE RESIDUE

LOG1=mdcm-nopatch-ref.out
LOG2=mdcm-patch-dev.out

[[ -f $LOG1 ]] && rm $LOG1
[[ -f $LOG2 ]] && rm $LOG2

ulimit -s 10240

mpirun -np $NPROC $REFCHARMM -i mdcm-nopatch-orig.inp -o $LOG1 >& errlog1
mpirun -np $NPROC $DEVCHARMM -i mdcm-patch-new.inp -o $LOG2 >& errlog2

echo "PATCHED TRIPEPTIDE WITH MONATOMIC ION, OLD CODE HAND-PATCHED PEPTIDE VS NEW CODE AUTO-PATCHED PEPTIDE"
echo
echo $LOG1
for i in "ENER>" "ENER INTERN>" "ENER EXTERN>" "ENER IMAGES>" "ENER EWALD>"; do grep "$i" $LOG1 | tail -1; done
echo

echo $LOG2
for i in "ENER>" "ENER INTERN>" "ENER EXTERN>" "ENER IMAGES>" "ENER EWALD>"; do grep "$i" $LOG2 | tail -1; done
echo
echo "CHECK FORCES AND VIRIAL:"
grep " ( " $LOG2 | grep -v "E"
